### ISSUE TITLE
Setting UID variables on lines 68 and 70 

### ISSUE THREAD

**Issue by mts299** [SuperDARNCanada/globus#1]
Currently users need to set these variables in the script:
PERSONAL_UUID = ''
CLIENT_ID = ''
, which is dangerous if they change something else. 

Proposed ideas to avoid this issue:
1. set environment variables
2. read from a configuration file 
3. they pass it into the python script as arguments

**Comment by kevinkrieger** [comment]
This issue has been fixed with pull request uuid_changes
