### ISSUE TITLE
Update Transfer didn't complete message

### ISSUE THREAD

**Issue by mts299** [SuperDARNCanada/globus#4]
Got this message running globus this morning:
`Transfer didn't complete yet but may still be running. Please check https://www.globus.org/app/activity if you want to check status of transfer`

However, this link has discontinued so we will need to update it to:
https://app.globus.org/activity

**Comment by kevinkrieger** [comment]
Thanks Marina, updated in https://github.com/SuperDARNCanada/globus/commit/dd85590c6039c4dc24138be0638b7287ff63e900
